### ISSUE TITLE
Etude de la cross-compilation de notre soft sur armadeus

### ISSUE THREAD

**Issue by simchanu29** [simchanu29/ENSTA-EmbSys-Projet#5]

**Comment by simchanu29** [comment]
Il faut compiler à la maison car le pare-feu de l'ensta bloque.

**Comment by MehdiN** [comment]
Pour la cross compilation: 

http://amgaera.github.io/blog/2014/04/10/cross-compiling-for-raspberry-pi-on-64-bit-linux/
